"""timestamptz, users.created_at, unique course code, quota and roster indexes

Revision ID: 1ca8b85b7626
Revises: c86676652ca2
Create Date: 2026-08-17 10:13:44.098073

Autogenerated, then adjusted: every timestamp <-> timestamptz conversion
carries an explicit USING clause. Without one Postgres interprets the
naive values in the *session's* TimeZone, so the result depends on who ran
the migration. Our container is Etc/UTC and the tables are empty, which
makes the implicit conversion identical today and wrong the first time
either of those changes.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1ca8b85b7626'
down_revision: Union[str, None] = 'c86676652ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NAIVE_TIMESTAMP_TABLES = (
    "enrollments",
    "gpu_reservations",
    "idempotency_keys",
    "reservations",
    "waitlist_entries",
)


def upgrade() -> None:
    for table in NAIVE_TIMESTAMP_TABLES:
        op.alter_column(
            table,
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
            existing_server_default=sa.text("now()"),
            postgresql_using="created_at AT TIME ZONE 'UTC'",
        )

    op.add_column(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )

    op.drop_index("ix_courses_code", table_name="courses")
    op.create_index(op.f("ix_courses_code"), "courses", ["code"], unique=True)

    op.create_index(
        "ix_gpu_reservations_user_status",
        "gpu_reservations",
        ["user_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_enrollments_offering_status",
        "enrollments",
        ["course_offering_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_reservations_user_id", "reservations", ["user_id"], unique=False
    )


def downgrade() -> None:
    op.drop_index("ix_reservations_user_id", table_name="reservations")
    op.drop_index("ix_enrollments_offering_status", table_name="enrollments")
    op.drop_index("ix_gpu_reservations_user_status", table_name="gpu_reservations")

    op.drop_index(op.f("ix_courses_code"), table_name="courses")
    op.create_index("ix_courses_code", "courses", ["code"], unique=False)

    op.drop_column("users", "created_at")

    for table in NAIVE_TIMESTAMP_TABLES:
        op.alter_column(
            table,
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            existing_nullable=False,
            existing_server_default=sa.text("now()"),
            postgresql_using="created_at AT TIME ZONE 'UTC'",
        )
